### ISSUE TITLE
Cannot open share project file libhdf5.so.10

### ISSUE THREAD

**Issue by MingkuanXu** [theislab/scvelo_notebooks#1]
Hi,

After successfully installing scvelo via pip,  I got the following error when running the first cell of DentateGyrus.ipynb.

The code I tried to run: import scvelo as scv
The error info I got:

ImportError                               Traceback (most recent call last)
<ipython-input-3-9d0da2a1e68d> in <module>
----> 1 import scvelo as scv
      2 # scv.logging.print_version()

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/scvelo/__init__.py in <module>
      5 del get_version
      6 
----> 7 from .read_load import AnnData, read, read_loom, load, read_csv
      8 from .preprocessing.neighbors import Neighbors
      9 from .tools.run import run_all

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/scvelo/read_load.py in <module>
----> 1 from .preprocessing.utils import set_initial_size
      2 
      3 import os, re
      4 import numpy as np
      5 import pandas as pd

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/scvelo/preprocessing/__init__.py in <module>
----> 1 from .utils import show_proportions, cleanup, filter_genes, filter_genes_dispersion, normalize_per_cell, log1p, \
      2     filter_and_normalize, recipe_velocity
      3 from .neighbors import pca, neighbors
      4 from .moments import moments

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/scvelo/preprocessing/utils.py in <module>
----> 1 from .. import logging as logg
      2 
      3 import numpy as np
      4 from scipy.sparse import issparse
      5 from sklearn.utils import sparsefuncs

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/scvelo/logging.py in <module>
    153 
    154 
--> 155 from anndata.logging import print_memory_usage
    156 from anndata.logging import get_memory_usage
    157 

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/anndata/__init__.py in <module>
----> 1 from .base import AnnData
      2 from .readwrite import (
      3     read_h5ad, read_loom, read_hdf,
      4     read_excel, read_umi_tools,
      5     read_csv, read_text, read_mtx,

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/anndata/base.py in <module>
     39             return 'mock zappy.base.ZappyArray'
     40 
---> 41 from . import h5py
     42 from .layers import AnnDataLayers
     43 

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/anndata/h5py/__init__.py in <module>
     22    SparseDataset
     23 """
---> 24 from .h5sparse import File, Group, SparseDataset, _load_h5_dataset_as_sparse
     25 from h5py import Dataset, special_dtype
     26 

/work/06211/mx31/stampede2/miniconda3/lib/python3.7/site-packages/anndata/h5py/h5sparse.py in <module>
      5 
      6 import six
----> 7 import h5py
      8 import numpy as np
      9 import scipy.sparse as ss

/opt/apps/intel18/impi18_0/python2/2.7.15/lib/python2.7/site-packages/h5py/__init__.py in <module>
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory

I also tried to install the latest version of scvelo but the error stayed the same. Is there anything  I could do to fix this?

**Comment by MingkuanXu** [comment]
Also is there a way to install scvelo by conda?

**Comment by yxian9** [comment]
you can try `module unload py2.7` from the system first.
