### ISSUE TITLE
scv.pl.scatter Gene not found error

### ISSUE THREAD

**Issue by mzhibo** [theislab/scvelo_notebooks#4]
Running scvelo 0.2.3 (python 3.7.9)

When I tried to plot gene expression along latent_time, it keep throwing the error of not valid gene name. Any suggestion how to fix this?

`var_names = ['Actn4', 'Ppp3ca', 'Cpe', 'Nnat']
scv.pl.scatter(adata, x='latent_time', y=var_names, frameon=False)`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-3cc0fdf9dd79> in <module>
      1 var_names = ['Actn4', 'Ppp3ca', 'Cpe', 'Nnat']
      2 scv.pl.scatter(adata, var_names, frameon=False)
----> 3 scv.pl.scatter(adata, x='latent_time', y=var_names, frameon=False)

~/anaconda3/envs/velocyto/lib/python3.7/site-packages/scvelo/plotting/scatter.py in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_outline, outline_width, outline_color, n_convolve, smooth, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    187                         **multi_kwargs,
    188                         **scatter_kwargs,
--> 189                         **kwargs,
    190                     )
    191                 )

~/anaconda3/envs/velocyto/lib/python3.7/site-packages/scvelo/plotting/scatter.py in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_outline, outline_width, outline_color, n_convolve, smooth, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    434                     else:
    435                         raise ValueError(
--> 436                             "x or y is invalid! pass valid observation or a gene name"
    437                         )
    438 

ValueError: x or y is invalid! pass valid observation or a gene name

**Comment by VolkerBergen** [comment]
I assume this if from line 13 in [DynamicalModeling.ipynb](https://github.com/theislab/scvelo_notebooks/blob/master/DynamicalModeling.ipynb)? 

Can you print `pd.Series(['Actn4', 'Ppp3ca', 'Cpe', 'Nnat']).isin(adata.var_names)`?
